planning_pipelines:
  pipeline_names:
    - ompl

ompl:
  planning_plugins:
    - ompl_interface/OMPLPlanner
  request_adapters:
    - default_planning_request_adapters/ResolveConstraintFrames
    - default_planning_request_adapters/ValidateWorkspaceBounds
    - default_planning_request_adapters/CheckStartStateBounds
    - default_planning_request_adapters/CheckStartStateCollision
  response_adapters:
    - default_planning_response_adapters/AddTimeOptimalParameterization
    - default_planning_response_adapters/ValidateSolution
    - default_planning_response_adapters/DisplayMotionPath
  start_state_max_bounds_error: 0.1
  planner_configs:
    RRTConnectkConfigDefault:
      type: geometric::RRTConnect
      range: 0.0
    PRMkConfigDefault:
      type: geometric::PRM
      max_nearest_neighbors: 10
    RRTstarkConfigDefault:
      type: geometric::RRTstar
      range: 0.0
      goal_bias: 0.05
      delay_collision_checking: 1
  aubo_arm:
    planner_configs:
      - RRTConnectkConfigDefault
      - PRMkConfigDefault
      - RRTstarkConfigDefault
    projection_evaluator: joints(aubo_shoulder_joint,aubo_upperArm_joint)
    longest_valid_segment_fraction: 0.005
    enforce_joint_model_state_space: true
